# Generated by Django 2.0.1 on 2018-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body_teaser',
            field=models.CharField(default='', max_length=400),
        ),
    ]
