# Generated by Django 2.0.1 on 2018-02-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180201_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('travel', 'TRAVEL'), ('attractions', 'ATTRACTIONS'), ('food', 'FOOD')], default='', max_length=50),
        ),
    ]
