# Generated by Django 2.0.1 on 2018-02-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180209_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('TRAVEL', 'TRAVEL'), ('ATTRACTIONS', 'ATTRACTIONS'), ('FOOD', 'FOOD')], default='', max_length=50),
        ),
    ]
