# Generated by Django 2.0.1 on 2018-02-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180209_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('TRAVEL', 'Travel'), ('ATTRACTIONS', 'Attractions'), ('FOOD', 'Food')], default='', max_length=50),
        ),
    ]
